name: deploy workflow
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: greet user
        run: echo welcome to github
        
  test:
    runs-on: ubunt-latest
    steps:
      - uses: actions/checkout@v3
      - name: greet user
        run: echo test in progress
        
  deploy:
    runs-on: ubunt-latest
    steps:
      - uses: actions/checkout@v3
      - name: greet user
        run: echo deploy completed
  
  
